name: findsgjobs_tmp
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas
  - requests
  - cryptography
  - authlib
  - python-dotenv
  - pip
  - pip:
      - streamlit
      - PyPDF2
      - python-docx
      - langchain
      - langchain-google-genai
      - langchain-community
      - langchain-tavily
      - google-generativeai
      - tavily-python
      - reportlab
