name: findsgjobs_app
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - pip
  - pip:
      - streamlit==1.32.2
      - pandas==2.1.4
      - requests==2.31.0
      - PyPDF2==3.20.1
      - python-docx==0.8.11
